import { Promotion } from "@/types/promotion";
import { addDays, subDays } from "date-fns";

export const promotionDatas: Promotion[] = [
    {
        id: "PROMO-001",
        code: "WELCOME20",
        name: "Welcome Discount",
        description: "20% off for new customers on their first order.",
        type: "percentage",
        value: 20,
        minSpend: 15.00,
        maxDiscount: 10.00,
        usageLimit: 1000,
        usedCount: 450,
        startDate: subDays(new Date(), 30),
        endDate: addDays(new Date(), 365),
        status: "active",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
    },
    {
        id: "PROMO-002",
        code: "SUMMER5",
        name: "Summer Sale Fixed",
        description: "$5.00 off on orders over $25.",
        type: "fixed_amount",
        value: 5.00,
        minSpend: 25.00,
        usageLimit: 500,
        usedCount: 500, // Fully used
        startDate: subDays(new Date(), 10),
        endDate: addDays(new Date(), 20),
        status: "inactive",
        createdAt: new Date("2024-05-15"),
        updatedAt: new Date("2024-06-05"),
    },
    {
        id: "PROMO-003",
        code: "FREEDEL",
        name: "Free Delivery Friday",
        description: "Free shipping on orders placed on Fridays.",
        type: "free_shipping",
        value: 0,
        minSpend: 10.00,
        usageLimit: null as any, // Unlimited
        usedCount: 1250,
        startDate: subDays(new Date(), 60),
        endDate: addDays(new Date(), 120),
        status: "active",
        createdAt: new Date("2024-02-10"),
        updatedAt: new Date("2024-02-10"),
    },
    {
        id: "PROMO-004",
        code: "FLASH50",
        name: "Flash Sale 50%",
        description: "Huge 50% discount for a limited time.",
        type: "percentage",
        value: 50,
        maxDiscount: 20.00,
        usageLimit: 100,
        usedCount: 100,
        startDate: subDays(new Date(), 5),
        endDate: subDays(new Date(), 1), // Past date
        status: "expired",
        createdAt: new Date("2024-06-01"),
        updatedAt: new Date("2024-06-01"),
    },
    {
        id: "PROMO-005",
        code: "B2BSPECIAL",
        name: "Wholesale Special",
        description: "15% off for bulk orders over $100.",
        type: "percentage",
        value: 15,
        minSpend: 100.00,
        maxDiscount: 50.00,
        usageLimit: 50,
        usedCount: 12,
        startDate: new Date(),
        endDate: addDays(new Date(), 30),
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "PROMO-006",
        code: "NEWYEAR25",
        name: "New Year 2025",
        description: "Prepare for 2025 with $10 off.",
        type: "fixed_amount",
        value: 10.00,
        minSpend: 40.00,
        usageLimit: 2000,
        usedCount: 0,
        startDate: new Date("2024-12-25"), // Future date
        endDate: new Date("2025-01-05"),
        status: "scheduled",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "PROMO-007",
        code: "LUNCHDEAL",
        name: "Lunch Time Deal",
        description: "Get $2.50 off during lunch hours.",
        type: "fixed_amount",
        value: 2.50,
        minSpend: 12.00,
        usageLimit: 5000,
        usedCount: 3420,
        startDate: subDays(new Date(), 90),
        endDate: addDays(new Date(), 90),
        status: "active",
        createdAt: new Date("2024-03-01"),
        updatedAt: new Date("2024-03-01"),
    },
    {
        id: "PROMO-008",
        code: "VIPMEMBER",
        name: "VIP Access",
        description: "Exclusive 30% discount for VIP tiers.",
        type: "percentage",
        value: 30,
        maxDiscount: 100.00,
        usageLimit: 500,
        usedCount: 215,
        startDate: subDays(new Date(), 150),
        endDate: addDays(new Date(), 215),
        status: "active",
        createdAt: new Date("2023-10-15"),
        updatedAt: new Date("2023-10-15"),
    },
];
