import { User } from "@/types/user";
import { subDays, subHours, subMinutes } from "date-fns";

export const userDatas: User[] = [
    {
        id: "USR-001",
        name: "Alice Johnson",
        email: "alice.j@example.com",
        role: "admin",
        status: "active",
        avatar: "https://i.pravatar.cc/150?u=alice",
        lastLogin: subMinutes(new Date(), 15),
        createdAt: subDays(new Date(), 365),
        updatedAt: subDays(new Date(), 2),
    },
    {
        id: "USR-002",
        name: "Bob Smith",
        email: "bob.smith@example.com",
        role: "manager",
        status: "active",
        avatar: "https://i.pravatar.cc/150?u=bob",
        lastLogin: subHours(new Date(), 2),
        createdAt: subDays(new Date(), 200),
        updatedAt: subDays(new Date(), 5),
    },
    {
        id: "USR-003",
        name: "Charlie Davis",
        email: "charlie.d@example.com",
        role: "staff",
        status: "inactive",
        avatar: "https://i.pravatar.cc/150?u=charlie",
        lastLogin: subDays(new Date(), 45),
        createdAt: subDays(new Date(), 150),
        updatedAt: subDays(new Date(), 45),
    },
    {
        id: "USR-004",
        name: "Diana Ross",
        email: "diana.r@example.com",
        role: "support",
        status: "active",
        avatar: "https://i.pravatar.cc/150?u=diana",
        lastLogin: subHours(new Date(), 5),
        createdAt: subDays(new Date(), 120),
        updatedAt: subDays(new Date(), 1),
    },
    {
        id: "USR-005",
        name: "Evan Wright",
        email: "evan.w@example.com",
        role: "staff",
        status: "pending",
        lastLogin: new Date(0), // Never logged in
        createdAt: subDays(new Date(), 1),
        updatedAt: subDays(new Date(), 1),
    },
    {
        id: "USR-006",
        name: "Fiona Gallagher",
        email: "fiona.g@example.com",
        role: "manager",
        status: "active",
        avatar: "https://i.pravatar.cc/150?u=fiona",
        lastLogin: subDays(new Date(), 1),
        createdAt: subDays(new Date(), 400),
        updatedAt: subDays(new Date(), 10),
    },
    {
        id: "USR-007",
        name: "George Costanza",
        email: "george.c@example.com",
        role: "support",
        status: "inactive",
        avatar: "https://i.pravatar.cc/150?u=george",
        lastLogin: subDays(new Date(), 90),
        createdAt: subDays(new Date(), 180),
        updatedAt: subDays(new Date(), 90),
    },
];
