import { User } from "@/types/user";
import { subDays, subHours, subMinutes } from "date-fns";

export const userDatas: User[] = [
    {
        id: "USR-001",
        name: "Alice Johnson",
        email: "alice.j@example.com",
        role: "admin",
        status: "active",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        lastLogin: subMinutes(new Date(), 15),
        createdAt: subDays(new Date(), 365),
        updatedAt: subDays(new Date(), 2),
    },
    {
        id: "USR-002",
        name: "Bob Smith",
        email: "bob.smith@example.com",
        role: "manager",
        status: "active",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        lastLogin: subHours(new Date(), 2),
        createdAt: subDays(new Date(), 200),
        updatedAt: subDays(new Date(), 5),
    },
    {
        id: "USR-003",
        name: "Charlie Davis",
        email: "charlie.d@example.com",
        role: "staff",
        status: "inactive",
        avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        lastLogin: subDays(new Date(), 45),
        createdAt: subDays(new Date(), 150),
        updatedAt: subDays(new Date(), 45),
    },
    {
        id: "USR-004",
        name: "Diana Ross",
        email: "diana.r@example.com",
        role: "support",
        status: "active",
        avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        lastLogin: subHours(new Date(), 5),
        createdAt: subDays(new Date(), 120),
        updatedAt: subDays(new Date(), 1),
    },
    {
        id: "USR-005",
        name: "Evan Wright",
        email: "evan.w@example.com",
        role: "staff",
        status: "pending",
        lastLogin: new Date(0), // Never logged in
        createdAt: subDays(new Date(), 1),
        updatedAt: subDays(new Date(), 1),
    },
    {
        id: "USR-006",
        name: "Fiona Gallagher",
        email: "fiona.g@example.com",
        role: "manager",
        status: "active",
        avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        lastLogin: subDays(new Date(), 1),
        createdAt: subDays(new Date(), 400),
        updatedAt: subDays(new Date(), 10),
    },
    {
        id: "USR-007",
        name: "George Costanza",
        email: "george.c@example.com",
        role: "support",
        status: "inactive",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        lastLogin: subDays(new Date(), 90),
        createdAt: subDays(new Date(), 180),
        updatedAt: subDays(new Date(), 90),
    },
];
