import { Category } from "@/types/category";

export const categoryDatas: Category[] = [
    {
        id: "cat-drinks",
        name: "Drinks & Beverages",
        description: "Refresh yourself with our wide variety of cold and hot drinks.",
        thumbnail: "/images/products/test-image.jpg",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "cat-chicken",
        name: "Fried Chicken",
        description: "Our signature crispy and juicy fried chicken.",
        thumbnail: "/images/products/test-image.jpg",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "cat-breakfast",
        name: "Breakfast",
        description: "Start your morning right with our breakfast combos.",
        thumbnail: "/images/products/test-image.jpg",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "cat-sides",
        name: "Sides & Snacks",
        description: "Perfect additions to complete your meal.",
        thumbnail: "/images/products/test-image.jpg",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "cat-burgers",
        name: "Burgers & Wraps",
        description: "Delicious burgers and wraps packed with flavor.",
        thumbnail: "/images/products/test-image.jpg",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "cat-desserts",
        name: "Desserts",
        description: "Sweet treats to end your meal on a high note.",
        thumbnail: "/images/products/test-image.jpg",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "cat-rice",
        name: "Rice Bowls",
        description: "Hearty rice bowls served with our signature meats.",
        thumbnail: "/images/products/test-image.jpg",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "cat-coffee",
        name: "Coffee",
        parentCategory: "cat-drinks",
        description: "Freshly brewed coffee for your daily fix.",
        thumbnail: "/images/products/test-image.jpg",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "cat-soda",
        name: "Soda",
        parentCategory: "cat-drinks",
        description: "Fizzy, carbonated drinks.",
        thumbnail: "/images/products/test-image.jpg",
        status: "inactive",
        createdAt: new Date(),
        updatedAt: new Date(),
    }
];
