import { Announcement } from "@/types/announcement";
import { addDays, subDays } from "date-fns";

export const announcementDatas: Announcement[] = [
    {
        id: "ANN-001",
        title: "System Maintenance Scheduled",
        content: "We will be performing scheduled maintenance on our servers this Sunday from 2 AM to 4 AM EST. During this time, the dashboard may be temporarily unavailable.",
        target: "all",
        status: "scheduled",
        publishDate: addDays(new Date(), 2),
        endDate: addDays(new Date(), 3),
        author: "Admin Team",
        isPinned: true,
        createdAt: subDays(new Date(), 1),
        updatedAt: subDays(new Date(), 1),
    },
    {
        id: "ANN-002",
        title: "New Feature: Custom Reports Release 🚀",
        content: "We are excited to announce the release of our new Custom Reports feature! You can now generate tailored analytics for your business needs directly from the Reports tab.",
        target: "customers",
        status: "active",
        publishDate: subDays(new Date(), 2),
        author: "Product Team",
        isPinned: true,
        createdAt: subDays(new Date(), 5),
        updatedAt: subDays(new Date(), 2),
    },
    {
        id: "ANN-003",
        title: "Holiday Schedule Update",
        content: "Please be advised that our customer support team will be operating on reduced hours during the upcoming holidays. Check the help center for the exact schedule.",
        target: "all",
        status: "active",
        publishDate: subDays(new Date(), 7),
        endDate: addDays(new Date(), 14),
        author: "HR Department",
        isPinned: false,
        createdAt: subDays(new Date(), 8),
        updatedAt: subDays(new Date(), 7),
    },
    {
        id: "ANN-004",
        title: "Q3 Townhall Meeting",
        content: "A quick reminder about our internal Q3 Townhall meeting tomorrow at 10 AM in the main conference room. Breakfast will be provided!",
        target: "employees",
        status: "active",
        publishDate: subDays(new Date(), 1),
        endDate: addDays(new Date(), 1),
        author: "Management",
        isPinned: false,
        createdAt: subDays(new Date(), 2),
        updatedAt: subDays(new Date(), 2),
    },
    {
        id: "ANN-005",
        title: "Deprecated API v1 Sunset",
        content: "The v1 API endpoints will be officially retired next month. Please ensure all your integrations are migrated to v2 to avoid service disruptions.",
        target: "customers",
        status: "active",
        publishDate: subDays(new Date(), 15),
        endDate: addDays(new Date(), 15),
        author: "Engineering",
        isPinned: false,
        createdAt: subDays(new Date(), 20),
        updatedAt: subDays(new Date(), 15),
    },
    {
        id: "ANN-006",
        title: "Flash Sale Alert ⚡️",
        content: "VIP members get early access to our Midnight Flash Sale starting tonight! Use your unique codes to claim 40% off selected items.",
        target: "vip",
        status: "expired",
        publishDate: subDays(new Date(), 30),
        endDate: subDays(new Date(), 28),
        author: "Marketing Dept",
        isPinned: false,
        createdAt: subDays(new Date(), 32),
        updatedAt: subDays(new Date(), 30),
    },
    {
        id: "ANN-007",
        title: "Office Relocation Details",
        content: "Our Seattle branch is moving to a new downtown location this weekend. Employees based there should review the moving guidelines emailed earlier today.",
        target: "employees",
        status: "inactive",
        publishDate: subDays(new Date(), 45),
        author: "Facilities Management",
        isPinned: false,
        createdAt: subDays(new Date(), 50),
        updatedAt: subDays(new Date(), 45),
    },
];
